### PR TITLE
Create loudoun_wildlife_conservancy.py

### PR DESCRIPTION
**Pull request by khayes847**
Create Loudoun Wildlife Conservancy web-scraper for all events through February 2020

### CODE REVIEW

**Comment by csmcallister** [comment]
Happy new year @khayes847 !

Do you want me to close #190 if this is its replacement?

Additionally,
- [ ] If an event doesn't have a cost, set the `Event Cost` field to `'0'` if it's definitely free or set it to an empty string `''` instead of setting it to `None`.
- [ ] add your module's test (see [this](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/.github/CONTRIBUTING.md#testing-your-code)).
- [ ] remove the latitude and longitude keys from each event dictionary, but leave your code that captures that data. Although it's awesome you were able to get those fields, the Capital Nature site doesn't currently support those fields :(

Feel free to holler if you've got questions. Here or on Slack works.

**Comment by khayes847** [comment]
Hi Scott,

Sorry about the duplicate pull requests. Since neither of the ones I
created include the test file, would it be possible to close both of them?
I can create a branch merge request.

I have a problem with the pricing category. Whenever there's a cost, the
website gives two different prices - one for members, one for non-members.
I've been adding both in dictionary form. However, the test won't allow the
value to be a dictionary. Should I just list the non-member price?

Best,
Kyle

**Comment by csmcallister** [comment]
You don't have to close the PR to add the test file. You can add new commits to this PR by:

checking out your local feature branch with:
`git checkout patch-2`

creating and editing your test file and then staging and committing it with:

```bash
git add .
git commit -m "TST: add test for loudoun wildlife (#16)"
git push
```

Once you push to your fork's remote like that, this PR will automatically update to reflect it.

As for the event costs, I think your right in listing the more expensive non-member cost. That way somebody who goes to that event based on what they see on the website will at worst be surprised to pay less instead of more if they're a member.

**Comment by khayes847** [comment]
Sorry for the wait, I went ahead and made the change, and pushed the
patch-2.

**Comment by khayes847** [comment]
Hey Scott,

No problem! Next time, I'll definitely have a lot smaller learning curve.

Best,
Kyle

**Pull request merged**
