### PR TITLE
Eventbrite chicken soup

### PR DESCRIPTION
**Pull request by Frankie-Figz**
Using the soup we scrape the event id's of the eventbrite webpage. With the event id's the API is hit for event information. The API is hit again to retrieve venue information via the venue_id field.

### CODE REVIEW

**Comment by csmcallister** [comment]
Looks good @Frankie-Figz!

Seems like we'd just need to plug in the organization id for any new Eventbrite organization. 

To get it done, could you:
 - [ ] get the event cost, if possible
 - [ ] get the event categories, if possible

**Comment by Frankie-Figz** [comment]
Thanks bud!

**Comment by csmcallister** [comment]
@Frankie-Figz you didn't have to close to keep working on this if you want to reopen.

**Comment by Frankie-Figz** [comment]
Hi Scott, I added the fixes and took the liberty of adding the python files for other required eventbrite classes (nova parks, sierra, fona, friends of kenilsworth, etc).

**Pull request merged**
