### PR TITLE
Added new feature- US arboretum

### PR DESCRIPTION
**Pull request by madhuqmar**
The update_event_data piece is more complex that it needs to be- but it gets the job done. Happy to update the code to make it more future-events-proof.

### CODE REVIEW

**Comment by csmcallister** [comment]
Thanks for the PR @madhuqmar!

I made a few in-line comments related to logging/error handling, but here's some other stuff:

- [ ] multi-day events such as [this one](https://www.usna.usda.gov/visit/calendar-of-events/ikebana-international-exhibit) need to have an event dict for each day. Right now, you have a single dict representing the event with a start date of 4/3 and and end date of 4/13. I've been meaning to clarify this in the schema docs, so my bad if that was unclear.
- [ ] Here's a [link](https://438-155925193-gh.circle-artifacts.com/3/lint-reports) to the lint report from the CircleCI build (you can also run it locally with `flake8 events/us_arboretum.py`). Most should be easy to fix.
- [ ] Add bullets three and four from [here](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/.github/CONTRIBUTING.md#what-to-contribute).

**Comment by madhuqmar** [comment]
Thanks @csmcallister! Can you submit your review so I can also view your comments? I'm unable to view them in this PR. Will be working on the other stuff you pointed out in the mean time.

**Comment by csmcallister** [comment]
Thanks for the updates @madhuqmar. Can you merge upstream master into your branch and then push again? See [this](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/.github/CONTRIBUTING.md#updating-a-pull-request) for a reference.

**Comment by madhuqmar** [comment]
Hi @csmcallister, I realized I wasn't working off of a branch, so I submitted a fresh pull request (feature/arboretum).

**Pull request closed without merging**
