### PR TITLE
Capital nature ingest sri

### PR DESCRIPTION
**Pull request by pasrpr**
Hi Scott,

Thanks for your valuable inputs. Made the changes. Please check and let me know when you get a chance.

Thanks,
Sri

### CODE REVIEW

**Comment by csmcallister** [comment]
All looks good, but the event output still has some events where `Event Venue Name` is `'No location'`. Those events need to be stripped from the output. The wordpress plugin is opinionated about this unfortunately 🤷‍♂️

**Comment by pasrpr** [comment]
Do you really think we should skip all the events with no location? Rather assign  Event Location as empty string?

**Comment by csmcallister** [comment]
The wordpresss plugin requires a venue name for some reason. It cannot be an empty string and it cannot be something like ‘no location’ afaik. @bmvoss, could you verify this?

**Comment by pasrpr** [comment]
Stripped events without location field. Changed fixtures accordingly. All the tests look good to me. Please check and let me know.

**Comment by bmvoss** [comment]
@csmcallister @pasrpr Yeah, if there is no location I don't think it makes sense to share the event. It's possible the location just hasn't been set yet, in which case you can make it 'TBD.'

**Comment by csmcallister** [comment]
@bmvoss If we can get away with putting TBD for the `Event Venue Name`, could we also just put something like `'See event website.'`?

**Comment by bmvoss** [comment]
I think that's okay. @ratherironic - do you know of any reason why that might not be a good idea to show a `Venue` as 'TBD' or 'See event website.'?

As long as there's a link to the event website, anyone who wants to attend can just use that to check for updates. The only problem I can imagine is, if a subsequent scrape pulls new info (like, the organizer added a location or start time), it would probably appear as a new event on our calendar. But I'm not sure there's any way of avoiding that...

**Comment by pasrpr** [comment]
Hi Scott,
Made the changes for location, please check and let me know.
Thanks,
Sri

**Comment by ratherironic** [comment]
@bmvoss  Hey! Sorry catching up on this. I don't know if there is a reason why it can't be TBD but we might not want to show that either way if they don't have location/venue determined given we're updating this only monthly and likely wont be going back and adding venue info after upload.

**Comment by csmcallister** [comment]
@ratherironic It's not that they don't have the venue/location determined but rather that scraping it is sometimes too difficult. I we can't be 100% positive that the venue/location we're extracting is correct, then we were thinking about making the venue `See event website`. Sound good?

**Comment by ratherironic** [comment]
@csmcallister That's perfect I think. Will test it and validate that is the case. If it's not, we if we could add that to the event description that would be perfect. Will confirm in a bit. Thanks!

**Comment by csmcallister** [comment]
@pasrpr DUG Network looks good, but I can't merge this PR because Kenilworth Gardens is throwing me an error (see below). Could you make a separate PR for Kenilworth Gardens, titling it something like `ENH: add Kenilworth Gardens event source`

Screen Shot 2019-03-08 at 7 56 34 PM

**Comment by pasrpr** [comment]
Hey Scott, 
Removed Friends Of Kenilworth Gardens, I think you should be able to merge DUG Network now. Let me know.
Thanks,
Sri

**Comment by csmcallister** [comment]
I’ll take a look tomorrow @pasrpr. Ran a marathon today and I’m absolutely wiped!

**Comment by pasrpr** [comment]
Sure. Take your time. Hope u enjoyed the run!

**Pull request merged**
