### PR TITLE
Refactor FONA eventbrite scraper to lambda function

### PR DESCRIPTION
**Pull request by dominicwhite**
Only tested locally so far.

### CODE REVIEW

**Comment by csmcallister** [comment]
@dominicwhite 
Just tried this using my own token. For reference, here's an event:
```python
[{'Event Name': 'February 18, 19, & 20 - Full Moon Hikes',
  'Event Organizer Name(s) or ID(s)': 'Friends of the National Arboretum',
  'Event Website': 'https://www.eventbrite.com/e/february-18-19-20-full-moon-hikes-tickets-53882309438?aff=ebapi',
  'Event Start Date': '2019-02-19',
  'Event Start Time': '12:00 AM',
  'Event End Date': '2019-02-19',
  'Event End Time': '02:00 AM',
  'Event Venue Name': '24th & R St NE / National Arboretum'}]
```

 - [ ] Strip the date out of the event name
 - [ ] Rename the `Event Organizer Name(s) or ID(s)` key to `Event Organizers`
 - [ ] Format the `Event End Time` and `Event Start Time` in 24hr time so that `02:00 AM` becomes `02:00:00`.
 - [ ] Strip the street address out of the `Event Venue Name`
 - [ ] Add the other required fields (see the bolded items in the [schema](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_schema.md))
 - [ ] Add the `Event Featured Image` field. The API seems to give an image url. These look nice on the calendar when we have them 😄 

If you really wanted to go above and beyond 🙏 , you could add some tests for your module in the tests directory. If you look at the other tests, there are some tests that will check to see if you've got the required data fields for each event and if the data types for each field are correct.

**Comment by dominicwhite** [comment]
@csmcallister Made all the schema changes except for stripping the date from the title. A lot of the FONA events have this, but there's no particular style to it. E.g.
_Winter Springhouse Run Volunteer Days - THURSDAYS in January/February 2019_
vs
_February 18th & 20th Full Moon - Forest Bathing_
vs
_February 18 & 20 - Full Moon Hikes_

I can try to filter some of these out if you'd like?

Also, none of the current events have categories associated with them in the Eventbrite API, but this is a required field. Currently I'm leaving it blank, but are there any default/standardized categories I can assign?

**Comment by csmcallister** [comment]
sweet work!

If there aren’t any categories, you can just pass an empty string.

As for the event titles, we can keep them as-is so long as you don’t mind opening an issue describing the current problem with those irregularly formatted dates. That way we can always revisit it.

Also, would you mind adding at least one test in the test directory? At the very least, call your main function (the one that produces the list of dicts), and then compare that to what’s expected (unittest’s assertCountEqual will do that).

**Comment by csmcallister** [comment]
Wooo!!! Commits!!!!

Just checked-out your branch and tried to run `handle_fona_eventbrite_api()` with my own API token. Encountered an error (note that the line #s might be slightly off):
```python
Traceback (most recent call last):
  File "events/fona.py", line 196, in <module>
    events = handle_fona_eventbrite_api()
  File "events/fona.py", line 139, in handle_fona_eventbrite_api
    fona_ingester.scrape()
  File "events/fona.py", line 124, in scrape
    self.parse_events()
  File "events/fona.py", line 114, in parse_events
    event_data[field] = self.field_handlers[field]['handler'](event, self.field_handlers[field]['keys'])
  File "events/fona.py", line 99, in handle_org
    'url': org_json['website'],
KeyError: 'website'
```

Also, @pasrpr adapted your Eventbrite class for [another event source](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/events/friends_of_kenilworth_gardens.py) so you might be able to pull from that.

**Comment by dominicwhite** [comment]
@csmcallister Wooo!! Thanks for the catch. Let me know what other changes you want to see - I hope to get as much done as possible before the next DataDive this weekend. At the very least I want to add some more/better tests.

Glad to hear the Eventbrite API class was useful to @pasrpr . At some point in the future (especially if we get more sources on Eventbrite) it might be useful to refactor all those scrapers to use a single source class so that we don't repeat ourselves too much.

**Pull request merged**
