### PR TITLE
BBARDC

### PR DESCRIPTION
**Pull request by hunjwaslike**
Here is my submission of the BBARDC scrape. I added a bunch of try and excepts since some events don't have all the necessary details. Let me know what changes you want made. 

Thanks,
Jaspreet

### CODE REVIEW

**Comment by csmcallister** [comment]
Great! I’ll take a look soon.

**Comment by csmcallister** [comment]
@hunjwaslike Could you please move `bbardc.py` to the `events/` directory within the repo?

**Comment by hunjwaslike** [comment]
> @hunjwaslike Could you please move `bbardc.py` to the `events/` directory within the repo?

I'm still trying to figure out how to use github. I think I moved the file. I'll get the hang of it.

**Comment by csmcallister** [comment]
@hunjwaslike thanks for moving that file. I ran it and it went off without a hitch! But doing so alerted me to the fact that your fork is very far behind this repository, which is the upstream. Before I merge, can you do a merge upstream master? Make sure you don't have any uncommitted changes locally before running the following:

```bash
cd <your repo>
git fetch upstream
git checkout master
git merge upstream/master
```

After you do that, you can `git push` to update this Pull Request. Then I can merge!

**Comment by hunjwaslike** [comment]
Hey Scott,

I’m glad the code worked for you.

I’m on vacation until Friday and I unfortunately didn’t bring my laptop.
Thank you for the directions, I will do the changes you asked on Friday
when I return. If there are any other websites you want scraped let me
know. I could use the practice.

Thanks,
Jaspreet

**Comment by csmcallister** [comment]
Enjoy the time off @hunjwaslike! There's a ton of event sources that need scraping in our issues backlog [here](https://github.com/DataKind-DC/capital-nature-ingest/issues). Feel free to check those out and claim one when you return.

**Comment by hunjwaslike** [comment]
Thanks! I will definitely do that.

**Comment by hunjwaslike** [comment]
Hey Scott,

I think you can merge now. Let me know if you need me to change anything. 

Thanks,
Jaspreet

**Comment by csmcallister** [comment]
I took a look at your output and noticed a few issues that need fixing:

- [ ] The `all_events` object should be a list containing a single dictionary for each event. It's currently a dictionary of dictionaries with the top-level keys being the `Event Name`. The `Event Name` needs to be a key:value pair within each event's dictionary alongside the other fields like `Event Organizer`.
- [ ] All of the `Event Website` fields contain https://bbardc.org/. They should be the event's individual website, such as https://bbardc.org/event/department-of-parks-and-recreation-hands-on-the-future/
- [ ] The `Event Organizer` field should always be *Building Bridges Across the River*
- [ ] The `Event Start Time` and `Event End Time` fields are not in the correct datetime format. You have values like `"9:30 pm"`. They need to be in 24-hour time like `21:30:00`.
- [ ] Some of your `Event Name`s are oddly formatted, e.g. `Ward 8 Homebuyer Club_2` and `C.R.I.S.P Farmshare & Market_14`. When googling that event, I found their [page](https://bbardc.org/event/ward-8-homebuyers-club/2019-03-02/) and can't see where that `_2` suffix is coming from. Could you nix these suffixes? We want this field almost above all others to be human readable. 
- [ ] The `Event Cost` field has a lot of `"N/A"` values. This field should be set to `'0'` for a free event or left blank (i.e. an empty string `""`. Otherwise you can specify the cost as a float converted to a string.
- [ ] The `export_events()` function should be renamed to `main()` and not accept any parameters. That means you'll need to move your definition of `link` on line 5 to within the scope of the function.
- [ ] `Address` isn't an acceptable field, but it is good that you're scraping it since we might one day want to use such geodata to create an events map as opposed to an events calendar. Please keep the code that's getting the addresses but don't insert it into the output.

The repo's [documentation](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_schema.md) spells out these data type requirements in more detail. 

Also, if you add a file to the `tests/` directory called `bbardc_test.py` and then copy-paste the following into it, you can run the test to see that you've met all of the above conditions. This will also allow CircleCI to run the test when you push to this PR.

Contents for your `tests/bbardc_test.py` file:
```python
from os import path
import sys
import unittest
sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))
from events.bbardc import main
from .utils import schema_test_required, schema_test_all, schema_test_types

class BBARDCTestCase(unittest.TestCase):
    '''
    Test cases for BBARDC events.
    '''

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_main(self):
        events = main()
        tests = [schema_test_required, schema_test_all, schema_test_types]
        for test in tests:
            with self.subTest(test = test):
                result = test(events)
                self.assertTrue(result)

if __name__ == '__main__':
    unittest.main()
```

**Comment by hunjwaslike** [comment]
I will get to work on fixing these errors tonight. 

Some of your Event Names are oddly formatted, e.g. Ward 8 Homebuyer Club_2 and C.R.I.S.P Farmshare & Market_14. When googling that event, I found their page and can't see where that _2 suffix is coming from. Could you nix these suffixes? We want this field almost above all others to be human readable.
The suffix is there because an event can happen multiple times per month. And since I was using the event name as a dictionary I couldn’t use the same name twice. I will figure out a better way to do this.

The Event Cost field has a lot of "N/A" values. This field should be set to '0' for a free event or left blank (i.e. an empty string "". Otherwise you can specify the cost as a float converted to a string.
There was no cost information on the website that I could find, thats why I used “N/A”. I will leave it blank.

All of the Event Website fields contain https://bbardc.org/. They should be the event's individual website, such as https://bbardc.org/event/department-of-parks-and-recreation-hands-on-the-future/ <https://bbardc.org/event/department-of-parks-and-recreation-hands-on-the-future/>
Shoot, this was working earlier. I will fix this.

I will add the unit testing and make sure everything is working 100% before I submit the changes. I should have this done by the end of the week.
Thanks,
Jaspreet

**Comment by csmcallister** [comment]
@hunjwaslike somebody else beat you to the punch and submitted code for this event source that I just merged with #146. Fortunately, there are at least 9 other event sources in our open [issues](https://github.com/DataKind-DC/capital-nature-ingest/issues) if you want to claim any of those. Just be sure you claim that event source with a comment in the issue so that others know you're on it.

**Comment by hunjwaslike** [comment]
Okay, thats fine, I thought I had claimed it. I will get started on the U.S. National Arboretum scrape. Have a good weekend.

**Pull request closed without merging**
