### PR TITLE
#76 adding condition to drop events without event website

### PR DESCRIPTION
**Pull request by kirakrishnan**
@csmcallister added condition to filter the events without website. checked the unittest cases aswell. let me know if I am missing anything

### CODE REVIEW

**Comment by csmcallister** [comment]
That conditional will work, but we should first try to get the event website for events that don't have a website listed in the API response. In the most recent scan (or if you run just the Arlington module again), you'll see that it's the Crosshairs Garage Races event that's missing an event website.

Here's how you could get an event website for it.

The scraper uses an events API. If that API doesn't have a website for an event in its results, then you can use the event name as a query parameter appended to this `https://today.arlingtonva.us/`. For Crosshairs Garage Races, that would be:  `https://today.arlingtonva.us/?search=%22Crosshairs%20Garage%20Races%22&date=%22All%20events%20in%20future%22"`. The resulting page should have results from which you can scrape an event website if the name of the event AND the event's date match. For this example, one of the matches would be `https://today.arlingtonva.us/event/39777`.

Then, if the above method fails, your conditional will make sure that event is dropped.

**Comment by kirakrishnan** [comment]
@csmcallister I made call to the api. But I am getting the event url field is none. If I make call to this url(`https://today.arlingtonva.us/?search=%22crosshairs%22&date=%22All%20events%20in%20future%22`) using selenium then I can get the event url . 

but as I was working on it. I observed that each event has a key called 'EventKey'. if I append this key to this url `https://today.arlingtonva.us/event/` it directs to the event website in our case this is the url for cross hairs. And this works for all the events. This way we can get the event website without any extra calls to api but not sure if this is a good solution.  I am uploading a file which has both the event website and eventkey for all the events for your reference.

let me know which solution sounds good either trying to load the web page using selenium or appending the event key to the above url.

**Comment by csmcallister** [comment]
woah @kirakrishnan! I’ll try to check out this elegant solution tha evening. Thanks for digging into this!

**Comment by kirakrishnan** [comment]
sure @csmcallister let me know your thoughts. I think even they are generating the urls for the events which do not have a custom url using the EventKey.

**Pull request merged**
