### PR TITLE
Kira casey trees

### PR DESCRIPTION
**Pull request by kirakrishnan**
Hi @abarciauskas-bgse @csmcallister This code extracts the calender events from casey trees. I dint test it with aws account. I checked if `event_output` is getting all the list of events in the correct format in `handler` function. I am using bs4 for the first time. let me know if I can do it in a different way to make it efficient or if I need to fix any errors.

### CODE REVIEW

**Comment by csmcallister** [comment]
Awesome work @kirakrishnan ! Just a few changes, which I admit are due to our lack of proper documentation. That's something I need to get on!

- [ ] Change the event dict keys to match those found in [event_schema.md](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_schema.md)
- [ ] Can you verify that you've got the correct `Event Venue Name` for the events. For example, for [this event](https://caseytrees.org/event/tree-advocates-brunch-performance-hearing-testimony-workshop/), you're output has `'Tree Advocates Brunch: Performance Hearing Testimony Workshop'` but the event website shows `Sospeso 1344 H Street NE  Washington, DC 20002 United States` as the location.
- [ ] Include an `Event Featured Image`, if possible.
- [ ] Include an `Event Description`, if possible.
- [ ] Include `Event Organizer Name(s) or ID(s)`
- [ ] Include `Event Cost`
- [ ] Include `Event Currency Symbol`
- [ ] Include `Event Time Zone` (you can just put 'Eastern Standard Time')
- [ ] Include the event categories delimited with commas in `Event Tags`. For example, [this event's](https://caseytrees.org/event/tree-advocates-brunch-performance-hearing-testimony-workshop/) tags would be `'Advocate,Class'`

If you want to go super above and beyond, you could also write a couple unit tests. [HTTPretty](https://httpretty.readthedocs.io/en/latest/introduction.html) is an excellent library for this as it allows you to mock the content of your get responses. That way you can control the html you scrape and not actually make a request during the test. You can see some examples of that [here](https://github.com/DataKind-DC/capital-nature-ingest/tree/master/lambdas/fairfax). If you're new to writing tests, then don't worry; I can try to handle it. But I'd also be happy to walk you through it!

**Comment by kirakrishnan** [comment]
Thanks @csmcallister . I made the changes to the fields which I understood and I have some queries. Please give me more info about them 

[ ]  Change the event dict keys to match those found in event_schema.md
-  changed all the keys to match schema. I was not able to find any keys for latitude, longitude and address. should I remove latitude and longitude completely. And for address should I append it to venue name or use an individual field?
[ ]   Can you verify that you've got the correct Event Venue Name for the events. For example, for this event, you're output has 'Tree Advocates Brunch: Performance Hearing Testimony Workshop' but the event website shows Sospeso 1344 H Street NE Washington, DC 20002 United States as the location.
- Thanks for noticing it. I fixed it. right now venue is just Sospeso and the rest is under address
[ ]   Include an Event Featured Image, if possible.
- added
[ ]   Include an Event Description, if possible.
- added
[ ]   Include Event Organizer Name(s) or ID(s)
- added
[ ]   Include Event Cost
- added
[ ]   Include Event Currency Symbol
- not sure from where to extract this. can I give value as 'USD'
[ ]   Include Event Time Zone (you can just put 'America/New_York')
- added
[ ]   Include the event categories delimited with commas in Event Tags. For example, this event's tags would be 'Advocate,Class'
- I am working on it. 

I read the documentation for HttPretty. I am little familiar with it now. Please walk me through it. 

Also I have included 2 files one with the complete data I am extracting and another is output file. Let  me know if you want me to add any other fields.

**Comment by csmcallister** [comment]
Keep the code you have to scrape the latitude, longitude and address fields, but don't insert them into the event dict for now. The WordPress Event plugin doesn't expect these fields, but we might eventually use their Map plugin, which would need those geo fields. 

For `Event Currency Symbol`, you can set the value to `'$'`. Britta actually unearthed [this reference](https://support.theeventscalendar.com/969953-CSV-file-examples-for-importing) that shows sample values for each of the fields. I'm going to update the ReadMe and schema shortly so that all of this is a bit more clear.

With testing, the idea is that you don't want your tests to actually make a request across the Internet to a website whose content is beyond your control. The trick is to fake a request and mock the response content. There's a variety of ways to do this, but I've found [HTTPretty's](https://github.com/gabrielfalcao/HTTPretty) API to be pretty straightforward. 

## HTTPretty Example:
Say you've got a function in `lambda_function.py` like this:
```python
def is_event_canceled(event_website):
    '''
    Returns True if the event site says the event has been canceled. False otherwise or None
    if a request error is encountered.
    '''
    try:
        r = requests.get(event_website)
    except:
        return
    content = r.content
    soup = BeautifulSoup(content, 'html.parser')
    page_title_lowered = soup.find('div', {'class':'page-title'}).text.strip().lower()
    if 'canceled' in page_title_lowered:
        return True
    else:
        return False
```
 
When testing this function, you'd want to check at least 3 cases: 
1. When the event site doesn't say the event has been canceled
2. When the event site says the event has been canceled
3. When the request encounters some sort of connection error beyond your control

Let's walk through the first test case. First, we need to create some mock content that we'd expect a request to an event website where the event hasn't been canceled to return. To do that, open up your terminal, pick one of your event websites (e.g. https://caseytrees.org/event/trees-101-2/), start up Python, and make a GET request:
```python
import requests
r = requests.get('https://caseytrees.org/event/trees-101-2/')
content = r.content
```
Above, `content` will contain a [bytes](https://docs.python.org/3.1/library/functions.html#bytes) object representing the html content of the page. Print that content (it'll be kind of long) and copy it to your clipboard. Create a `test_fixtures.py` file that lives in the same directory as `lambda_function.py` and create an object in there to hold that content:

```python
event_website_content = b'<!DOCTYPE html>\n<html  lang="en" dir="ltr" prefix="content: 
http://purl.org/rss/1.0/modules/content/ ..........'
```

Now that you've got some mock content to work with, you can write that first test. In `test.py` (same directory as `lambda_function.py` and `test_fixtures.py`) you could then do something like this:

```python
import unittest
import httpretty
import requests
from lambda_function import is_event_canceled
from test_fixtures import event_website_content

class CaseyTreesTestCase(unittest.TestCase):
    
    def setUp(self):
        self.event_website = 'https://caseytrees.org/event/trees-101-2/'
        self.event_website_content = event_website_content

    def tearDown(self):
        self.event_website = None
        self.event_website_content = None

    @httpretty.activate
    def test_is_event_canceled(self):
        #this is where you mock the request
        httpretty.register_uri(method=httpretty.GET,
                                            uri=self.event_website,
                                            status=200,
                                            body=self.event_website_content)
        result = is_event_canceled(self.event_website)
        expected = False
        self.assertEqual(result, expected)

if __name__ == '__main__':
    unittest.main()
```

This is just one way (using HTTPretty) to mock a request. There's also the [requests-mock](requests-mock) library and the standard mock module from unittest (see [this SO post](https://stackoverflow.com/questions/15753390/how-can-i-mock-requests-and-the-response)). The method you choose is up to you!

**Comment by kirakrishnan** [comment]
Hi @csmcallister . I removed the latitude, longitude and address fields insertion into the result. And I updated the `Event Currency Symbol` with `$`. 

Thanks for the HTTPretty example. I tried to write couple unit tests using the example. can you check if it looks good.

**Comment by csmcallister** [comment]
@kirakrishnan I cloned your feature branch and then tried running the tests in `kira-capital-nature-ingest/lambdas/casey_trees` with:
```bash
python -m unittest test.py
```

`test_handle_ans_page_success` failed with this:
```bash
/Users/mcallistercs/anaconda/lib/python3.6/site-packages/httpretty/core.py:495: ResourceWarning: unclosed file <_io.BufferedRandom name=7>
  self.fd = FakeSockFile()
./Users/mcallistercs/anaconda/lib/python3.6/site-packages/httpretty/core.py:495: ResourceWarning: unclosed file <_io.BufferedRandom name=8>
  self.fd = FakeSockFile()
/Users/mcallistercs/anaconda/lib/python3.6/site-packages/bs4/__init__.py:520: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 0)>
  self.currentTag, self._most_recent_element)
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
/Users/mcallistercs/anaconda/lib/python3.6/site-packages/httpretty/core.py:554: ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.0.180', 57510), raddr=('52.206.214.15', 443)>
  self.real_sendall(data)
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
F
======================================================================
FAIL: test_handle_ans_page_success (test.CaseyTreesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mcallistercs/anaconda/lib/python3.6/site-packages/httpretty/core.py", line 1702, in wrapper
    return test(*args, **kw)
  File "/Users/mcallistercs/Desktop/Github/kira-capital-nature-ingest/lambdas/casey_trees/test.py", line 70, in test_handle_ans_page_success
    self.assertEqual(result, expected)
AssertionError: Lists differ: [{'Event Name': 'Trees 101', 'Event Website': 'htt[1969 chars]es'}] != [{'Event Tags': ['tribe-events-category-care', 'tr[1975 chars]30'}]

First differing element 1:
{'Event Name': 'Tree Advocates Meetings Parts 1 &[1027 chars]ees'}
{'Event Tags': ['tribe-events-category-advocate',[1033 chars]:30'}

Diff is 2947 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 2 tests in 6.180s

FAILED (failures=1)
```

At first I thought this was due to you using assertEqual instead of [assertCountEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual), but when I made that change the test still failed.  To see where the discrepancy is between expected and result, you can add a `maxDiff` attribute to the CaseyTreesTestCase class like this:

```python
class CaseyTreesTestCase(unittest.TestCase):

    def setUp(self):
        self.event_website = 'https://caseytrees.org/event/trees-101-2/'
        self.event_website_content = event_website_content
        self.maxDiff = None
```

Then the diff will print out when you rerun the test.

**Comment by kirakrishnan** [comment]
@csmcallister  The function works like this when we give the `feb month url`. It will extract all the events for `feb`. and check if there is a link for `march` and If there is that url is passed as input to function so all the events from march are extracted and then the process goes on. In my previous test code I dint mock the `march url`. I think that is the reason the test case failed. once I mocked the march month the test case is running but even then I am seeing the same issue. can I ignore it as it is running else can you give me some directions.

`python -m unittest test.py`

`/anaconda3/lib/python3.7/site-packages/httpretty/core.py:495: ResourceWarning: unclosed file <_io.BufferedRandom name=6>
  self.fd = FakeSockFile()
./anaconda3/lib/python3.7/site-packages/httpretty/core.py:495: ResourceWarning: unclosed file <_io.BufferedRandom name=7>
  self.fd = FakeSockFile()
/anaconda3/lib/python3.7/site-packages/bs4/element.py:252: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 0)>
  self.parent = parent
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
/anaconda3/lib/python3.7/site-packages/bs4/element.py:883: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 0)>
  self.parser_class = parser.__class__
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
<unknown>:1: DeprecationWarning: invalid escape sequence \/
.
----------------------------------------------------------------------
Ran 2 tests in 0.098s

OK`

**Comment by csmcallister** [comment]
@kirakrishnan the tests look good! Only issues that remain are with the `Event Description` and `Event Tags` fields.

### Event Description
I saw that you're using BS4 to get an event's data from `'script',{'type':'application/ld+json`. Unfortunately, longer fields in [JSON-LD](https://en.wikipedia.org/wiki/JSON-LD) are sometimes truncated. You can see that in the [trees 101 event](https://caseytrees.org/event/trees-101-2/):

```
'Event Description': '&lt;p&gt;Do you want to play a greater role in re-treeing D.C.? We need
 your help to protect and promote trees in our urban forest! Trees 101 provides a 
foundation in tree anatomy, basic tree identification and an overview of how 
trees function to provide the benefits we enjoy in the urban forest. The class 
will [&hellip;]&lt;/p&gt;\\n'
```

To get the rest of that description's paragraph, you could scrape the event page's content (looks like you'll want the first 1-2 `<p>` tags with the `MsoNormal` class). Alternatively, you could checkout [rdflib-jsonld](https://github.com/RDFLib/rdflib-jsonld), which might help you parse the JSON-LD using the schema.org context it provides.

### Event Tags
These need a little formatting and also need to be changed from a list to a string of comma delimited tags. For example, `['tribe-events-category-care', 'tribe-events-category-class']` becomes `'care, class`'.

Once you make those changes in `lambda_function.py`, don't forget to update the expected values in your tests. I always forget to do that 🤕

**Comment by kirakrishnan** [comment]
@csmcallister I have updated event tags field to display the content as string and updated the expected values in test.  I am still trying to figure out how to extract event description fields. let me know if you find anything

**Comment by csmcallister** [comment]
The tags look good. As for the description, let's keep it simple and use that description in the meta tag.  It's not complete, but at least it's consistent and ends with an ellipsis.

**Comment by kirakrishnan** [comment]
sounds good @csmcallister . I added a new function which will get event description and added a unittest for it. let me know if you want me to make any changes.

**Comment by csmcallister** [comment]
One final thing with the Event Description and the Event Name. 

For the Event Description, some latin-1 characters (e.g. `\xa0`) need to be stripped out. The following will do that:
```python
import unicodedata
s = 'Join\xa0the …'
s = unicodedata.normalize('NFKD',s)
print(s)
'Join the ...'
```

For the Event Name, you've got some html in the string. You can format that like:
```python
from bs4 import BeautifulSoup
s = 'Tree Advocates Meetings Parts 1 &#038; 2: Budget Hearings Discussion &#038; Workshop'
soup = BeautifulSoup(s)
soup.get_text()
'Tree Advocates Meetings Parts 1 & 2: Budget Hearings Discussion & Workshop'
```

After that you'll be good to go!

**Comment by kirakrishnan** [comment]
@csmcallister done. Thank you for your patience

**Comment by csmcallister** [comment]
🎉 @kirakrishnan

**Pull request merged**
