### PR TITLE
ENH: add scraper for Riverkeeper (#132)

### PR DESCRIPTION
**Pull request by NicoleJaneway**

### CODE REVIEW

**Comment by csmcallister** [comment]
@NicoleJaneway Dont' worry about the failed test. That error is from another scraper. I fixed that error and merged the fix into the master branch, which creates a good opportunity for you to handle a "stale" pull request. By "stale", I mean that your pull request doesn't include the most recent code (i.e. that fix I just made). You can incorporate this new stuff into your PR by doing what's often referred to as a "merge upstream master". You can do this with the following:

```bash
cd <path/to/your/local/repo>
git checkout riverkeeper
git fetch upstream
git merge upstream/master
git push origin riverkeeper
```

Holler if you've got any questions. After you do this, you can follow the [contributing](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/.github/CONTRIBUTING.md) guidelines to add your test and update a couple lines in `get_events.py`.

**Comment by NicoleJaneway** [comment]
Hey @csmcallister, I attempted to merge the upstream master, and got back that everything is up-to-date.  Is that the outcome you were expecting?  
Screen Shot 2019-09-25 at 10 38 25 AM

**Comment by csmcallister** [comment]
@NicoleJaneway The `git merge` failed because, as you can see after your `git checkout` command, you've added/modified files while on your branch that were later updated in the upstream repo. That's why you get the error after `git merge`; it's git's way of saying that they won't overwrite your local version of those files with the newer ones unless you save your local versions (e.g. by using something called "git stash"). We don't want to save your local versions, so try these commands:

```bash
git checkout riverkeeper
git checkout -- .
```
The above will checkout your riverkeeper branch and discard those local changes. To validate this,
run `git status`. You should see a message like this:

```bash
On branch riverkeeper
Your branch is up to date with 'origin/riverkeeper'.

nothing to commit, working tree clean
```

If so, then try the merge again with:
```bash
git fetch upstream
git merge upstream/master
```

If there are no conflicts (or if they could be fixed automatically), a file with a default commit message will open up in terminal. Your terminal has built-in text editors, which is what'll appear if all goes well. You can simply save and quit this file by typing `esc` and then `ZZ` (that's holding down shift and type 'z' twice).

Let me know how that goes!

**Comment by NicoleJaneway** [comment]
@csmcallister here's the message I'm seeing after discarding changes

Screen Shot 2019-09-25 at 11 51 09 AM

**Comment by csmcallister** [comment]
I've never seen that message before, but a quick visit to SO proposes two options in the top ✅  answer: https://stackoverflow.com/questions/13361729/found-a-swap-file-by-the-name

You likely have a terminal open elsewhere with an unfinished git session. Simplest option might be competely exiting out of all your text editors and terminals (using cmd + q) and then opening a fresh terminal to try the process again.

**Comment by NicoleJaneway** [comment]
@csmcallister apologies for not checking SO beforehand - that will be my go to for future.  I think we should be good now?  Any further action required from me?

**Comment by csmcallister** [comment]
Were you able to successfully merge upstream master? 

If so, the next step is to add your test and an updated get_events.py to your riverkeeper branch. It appears you did these things but while on separate branches called patch-1, patch-2, and patch-3. You need to be sure you're on the riverkeeper branch when you create/modify these files - and that you do this after merging upstream master.

**Comment by NicoleJaneway** [comment]
@csmcallister getting an error

image

Is there an issue with my requirements that's preventing the 'requests' module from coming through?

**Comment by csmcallister** [comment]
It doesn't appear that you've activated a virtual environment, which is why python can't find requests. When you're in the root of the repo, do the following

```bash
source env/bin/activate
```

That should work since we used the built-in `venv` library together to make that env directory to hold the project's dependencies. You'll know this activated your environment if your command prompt changes to look something like `(env)Nicoles-MacBook-Pro....` after that above command.

With the environment activated, try running the test again, but do so from the root of the repo instead of from within the tests directory with:

```bash
python3 -W ignore -m unittest tests/riverkeeper_test.py
```

I need to update the contributing guidelines to specify that you need to run the tests relatively from the root of the directory since I recently updated the CircleCI configuration, so that's not on you!

**Comment by NicoleJaneway** [comment]
@csmcallister okay, I think I've redone the merge from Master and incorporated the new test and updated get_events file.  Let me know what else I need to do, and thanks again for your help :)

**Comment by csmcallister** [comment]
Everything looks good @NicoleJaneway ! Thanks for making this contribution 🎉 and congrats on your first open source contribution with this PR 🎆

**Pull request merged**
