### PR TITLE
Create tnc.py

### PR DESCRIPTION
**Pull request by sparklingjourney**
Event data for The Nature Conservancy (Virginia) from Ayan

### CODE REVIEW

**Comment by csmcallister** [comment]
Great work so far @sparklingjourney !

Here's some edits to make this PR happen:

 - [ ] Wrap the following global variables in a function or two that is then called from within `main()`:
```python
url = 'https://uv6jfqw6q8.execute-api.us-east-1.amazonaws.com/prod/search?q=*&q.parser=lucene&fq=(and%20template_name:%27eventdetailpage%27search_by_domain:%27nature_usa_en%27(or%20geographic_location:%27all_locations%27(and%20event_region_title:%27United%20States%27event_locale_title:%27Virginia%27))event_start_date:%20%5B%272019-02-19T00:00:00Z%27,%7D)&sort=event_start_date_sort%20asc&size=200'
html_doc = requests.get(url).content

page = requests.get(url)
soup = bs4.BeautifulSoup(page.content, 'html.parser')

soup=str(soup)
events=json.loads(soup)

events.keys()
hits=events['hits']

hits.keys()
hit=hits['hit']
```
- [ ] Format the `Event Start Date` and `Event End Date` fields. Right now, you have datetime objects for values. They need to be strings like `'21:30:00'`
- [ ] Format the `Event Start Time` and `Event End Time` fields. Right now, you have datetime objects for values. They need to be strings like `'1965-12-31'`
- [ ] The `Event Description` fields need trailing whitespace stripped. `str.strip()` will do that.
- [ ] The `Event Venue Name` field cannot be blank. It looks like this field ins't in the API you're able to call, but it can be scraped from an event's website (e.g. https://www.nature.org//en-us/get-involved/how-to-help/volunteer-and-attend-events/find-local-events-and-opportunities/japanese-barberry-invasive-control/). 
 - [ ] The `Event Category` field needs to be a string of comma delimited categories. You have a list. You can convert it with `", ".join(category_list)`
- [ ] The `Timezone` field should be `'America/New_York'`
- [ ] The `Event Organizers` field is mandatory and should be the event source, which is `'The Nature Conservancy (Virginia)'`
- [ ] If an event is recurring (like the `'Japanese Barberry Invasive Control'`), I *think* we need to represent each date upon which it occurs with its own event dictionary. That way the output csv has a separate row for each of the days that event falls on. But I'm not 100% sure how the Wordpress Events plugin works:  @ratherironic or @bmvoss might be able to shed light on that.

Finally, if you're familiar at all with writing tests, please add some unit/integration tests to the `tests/` directory in the root of this project. 
At a minimum, you should have a test that asserts the result of your script being equal to what's expected by the schema. This makes it easier to review the event output.

If you're not too familiar with tests, here's some boiler plate you should be able to pretty easily adapt.

```python
#name this file tnc_test.py
import unittest
from events.tnc import main
import sys
from os import path
sys.path.append( path.dirname( path.dirname( path.abspath(__file__) ) ) )

class MyEventsTestCase(unittest.TestCase):
    '''
    Test cases for My Events
    '''
    
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_get_my_events(self):
        result = main()
        #update this expected object below to contain what the data is supposed to look like
        #since hard-coding the expected can take a lot of lines, there's a tests/fixtures directory
        #where you can put this expected value and then import into here.
        expected = [{
                    "Event Cost": "0",
                    "Event Currency Symbol": "$",
                    "Event Description": "foo",
                    "Event End Date": "2019-01-27",
                    "Event End Time": "12:00:00",
                    "Event Name": "baz",
                    "Event Organizers": "buz",
                    "Event Start Date": "2019-01-27",
                    "Event Start Time": "10:00:00",
                    "Timezone": "America/New_York",
                    "Event Venue Name": "Dawson Terrace",
                    "Event Website": "https://www.fizbuz.com",
                    "All Day Event":False}]
        self.assertEqual(result, expected)
        
if __name__ == '__main__':
    unittest.main()
```

Then, to run this test, navigate into the tests directory
```bash
cd tests/
```
And then run the tests:
```bash
python3 -m unittest tnc_test.py
```
If the test succeeds, it'll say `OK`.

**Comment by bmvoss** [comment]
Thanks @sparklingjourney & @csmcallister !

Re: recurring events, you're right, each instance should have its own output line in the Events csv, so an event that happens every Sunday would have a separate output for each week. If it's a multi-day event, like Saturday through Sunday, that can be a single output.

**Comment by sparklingjourney** [comment]
Thanks @bmvoss ! I understand this is a multi-day event!

I am working on the other edits today!

**Comment by sparklingjourney** [comment]
@csmcallister I have requested a pull of the updated script according to all your comments except that I keep it as a multi-day single event (I understand it is not recurring). I am not familiar with the test, so it may be easier to talk with you in person at the next meetup! Thanks again!

**Comment by csmcallister** [comment]
Great to see all those changes! Only a few things remaining:

- [ ] Break out those recurring events. Your output needs to have an event dictionary for each one of an event's dates. Take the bird sign installation event. Right now, your output has just one event dict:

```python
{'Event Start Date': '2019-04-10',
 'Event End Date': '2019-04-30',
 'Event Start Time': '10:00:00',
 'Event End Time': '14:00:00',
 'Event Website': 'https://www.nature.org/en-us/get-involved/how-to-help/volunteer-and-attend-events/find-local-events-and-opportunities/bird-sign-installation/',
 'Event Name': 'Bird Sign Installation',
 'Event Description': 'Volunteers are needed to post signs on Virginia Coast Reserve barrier islands notifying visitors about important bird nesting and resting areas.',
 'Event Venue Name': 'Virginia Coast Reserve barrier islands',
 'All Day Event': False,
 'Event Category': 'Topic, activities, volunteering',
 'Event Cost': '',
 'Event Currency Symbol': '$',
 'Timezone': 'America/New_York',
 'Event Organizers': 'The Nature Conservancy (Virginia)'}
```

But the API lists multiple dates in its response:

```python
{'id': '9e37b7de-9df1-4897-9e7c-74b83893a045',
 'fields': {'event_title': 'Bird Sign Installation',
  'topic': ['activities', 'topic', 'volunteering'],
  'geographic_location': ['geographic_location', 'united_states', 'virginia'],
  'event_timezone': 'ET (UTC -05:00h)',
  'event_start_date_sort': '2019-04-10T15:00:01Z',
  'event_dates': 'Apr 10 - Apr 30, 2019',
  'title': 'Bird Sign Installation',
  'description': 'Volunteers are needed to post signs on Virginia Coast Reserve barrier islands notifying visitors about important bird nesting and resting areas. ',
  'topic_title': ['Topic', 'activities', 'volunteering'],
  'event_all_day': 'no',
  'link': '/en-us/get-involved/how-to-help/volunteer-and-attend-events/find-local-events-and-opportunities/bird-sign-installation/',
  'event_recurring': 'no',
  'event_timings': '10:00 AM - 02:00 PM',
  'document_type': 'page',
  'business_group_title': ['Business Group', 'United States', 'Virginia'],
  'event_end_date': ['2019-04-30T19:00:01Z'],
  'search_by_domain': 'nature_usa_en',
  'event_start_date': ['2019-04-10T19:00:01Z',
   '2019-04-11T19:00:01Z',
   '2019-04-12T19:00:01Z',
   '2019-04-13T19:00:01Z',
   '2019-04-14T19:00:01Z',
   '2019-04-15T19:00:01Z',
   '2019-04-16T19:00:01Z',
   '2019-04-17T19:00:01Z',
   '2019-04-18T19:00:01Z',
   '2019-04-19T19:00:01Z',
   '2019-04-20T19:00:01Z',
   '2019-04-21T19:00:01Z',
   '2019-04-22T19:00:01Z',
   '2019-04-23T19:00:01Z',
   '2019-04-24T19:00:01Z',
   '2019-04-25T19:00:01Z',
   '2019-04-26T19:00:01Z',
   '2019-04-27T19:00:01Z',
   '2019-04-28T19:00:01Z',
   '2019-04-29T19:00:01Z',
   '2019-04-30T19:00:01Z']}}
```
I think there are 21 separate start dates up there. So you'd need 21 separate bird signage events in your output.

- [ ] Use datetime.now() to programmatically create the API url's `event_start_date` query. That way we get relevant results when running this module in the future. Right now, a February start-date is hardcoded into the url.

- [ ] All of your scraper's code is inside the main function. To make testing simpler, you'll want to refactor your code so that there are separate functions for each piece of your scraper's logic. Then those functions are called sequentially within main. As an example, take the task fo calling the API and getting the JSON response. A separate function that does just that might look like:

```python
def get_api_events():
    url = 'https://uv6jfqw6q8.execute-api.us-east-1.amazonaws.com/prod/search?q=*&q.parser=lucene&fq=(and%20template_name:%27eventdetailpage%27search_by_domain:%27nature_usa_en%27(or%20geographic_location:%27all_locations%27(and%20event_region_title:%27United%20States%27event_locale_title:%27Virginia%27))event_start_date:%20%5B%272019-02-19T00:00:00Z%27,%7D)&sort=event_start_date_sort%20asc&size=200'
    try:
        r = requests.get(url)
    except:
        sys.exit(1)
    data = r.json() 
    events=data['hits']['hit']
     
    return events

events = get_api_events()
```

**Comment by sparklingjourney** [comment]
@csmcallister I believe I have fulfilled all your new requests and made a new commit now. I especially like the example in your last comment which make the codes more concise (not very clear about the try and except though). Still not familiar with the test.

**Comment by csmcallister** [comment]
Great @sparklingjourney !

I'll try to take a look this evening. In the meantime, here's a good [resource explaining error handling](https://realpython.com/python-exceptions/) in Python, which is what the `try:except` block is for.

**Comment by sparklingjourney** [comment]
@csmcallister I thought only when there is exception error will the system exists. Could I just remove the try and except?

**Comment by sparklingjourney** [comment]
@csmcallister I made another commit. sorry there was a reference error it seems that somehow did not show when I was running the codes in my local notebook earlier

**Comment by csmcallister** [comment]
You're right about the exit when the exception happens, but if the script exits, then the other scrapers won't be able to run.

And don't sorry about the failing Circle I checks right now. I'll need to change something in the config for that to fix itself.

**Comment by sparklingjourney** [comment]
Ok

**Comment by csmcallister** [comment]
@sparklingjourney I made some fixes to your PR in d0081d2. Holler if you've got questions. 

Once I get a chance to write some tests locally and show that they pass, I'll merge.

**Comment by sparklingjourney** [comment]
@csmcallister This is awesome!! Thank you so much for the enhancement!! It would be great to learn more :)

**Pull request merged**
